# Generated by Django 2.2.1 on 2020-08-19 12:34

from django.db import migrations, models
import utilities.helper


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20200819_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultImage',
            new_name='AutoImage',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='uploads/profile/1/1594598724.png', upload_to=utilities.helper.Helper.user_upload_file_name),
        ),
    ]
