# Generated by Django 2.2.1 on 2020-08-30 08:14

from django.db import migrations, models
import utilities.helper


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_auto_20200830_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='uploads/default_img/team-8.png', upload_to=utilities.helper.Helper.user_upload_file_name),
        ),
    ]
