# Generated by Django 2.2.1 on 2020-09-05 18:42

from django.db import migrations, models
import utilities.helper


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20200830_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='uploads/default_img/team-7.png', upload_to=utilities.helper.Helper.user_upload_file_name),
        ),
    ]
