# Generated by Django 2.2.1 on 2020-09-05 22:51

from django.db import migrations, models
import utilities.helper


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20200905_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday_msg_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='uploads/default_img/team-5.png', upload_to=utilities.helper.Helper.user_upload_file_name),
        ),
    ]
