# Generated by Django 2.2.1 on 2020-07-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0012_auto_20191208_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='total_score',
            new_name='team_a_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='total_score',
        ),
        migrations.AddField(
            model_name='attempt',
            name='team_b_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='team_a_score',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='team a score'),
        ),
        migrations.AddField(
            model_name='question',
            name='team_b_score',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='team b score'),
        ),
    ]
