# Generated by Django 2.2.1 on 2020-07-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0013_auto_20200711_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='team_a_score',
            new_name='total_score',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='team_b_score',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='total_corner_kicks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='team_a_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='team_b_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='total_corner_kicks',
        ),
        migrations.AddField(
            model_name='question',
            name='penalty',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Penalty'),
        ),
        migrations.AddField(
            model_name='question',
            name='total_score',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='total score'),
        ),
        migrations.AlterField(
            model_name='question',
            name='total_cards',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='total card'),
        ),
    ]
