# Generated by Django 2.2.1 on 2020-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0014_auto_20200713_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='new',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='New'),
        ),
    ]
