# Generated by Django 2.2.1 on 2020-07-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0015_attempt_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='penaltya',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Penalty'),
        ),
    ]
