# Generated by Django 2.2.1 on 2020-07-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0016_attempt_penaltya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='new',
        ),
    ]
