# Generated by Django 2.2.1 on 2020-07-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0018_attempt_attempt_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='day_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
