# Generated by Django 2.2.1 on 2020-08-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0020_auto_20200714_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='team_a_logo',
            field=models.ImageField(null=True, upload_to='uploads/trivia_img'),
        ),
        migrations.AlterField(
            model_name='question',
            name='team_b_logo',
            field=models.ImageField(null=True, upload_to='uploads/trivia_img'),
        ),
    ]
