# Generated by Django 2.2.1 on 2020-08-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0021_auto_20200817_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='team_b_logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/trivia_img'),
        ),
    ]
