# Generated by Django 2.2.1 on 2020-08-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0017_auto_20191104_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False, null=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack.WeekEndRaffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack.RafflePlayer')),
            ],
        ),
        migrations.CreateModel(
            name='BonusButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack.RafflePlayer')),
            ],
        ),
    ]
