# Generated by Django 2.2.1 on 2020-08-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0021_auto_20200804_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleplayer',
            name='get_bonus',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
