# Generated by Django 2.2.1 on 2020-07-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='age',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
