# Generated by Django 2.2.1 on 2020-07-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_selfquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfquestion',
            name='answer',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
