# Generated by Django 2.2.1 on 2020-07-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_selfquestion_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfquestion',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
